version: "3.8"

services:
  backend:
    build:
      context: ./chatflow-backend
      dockerfile: Dockerfile
    container_name: chatflow_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: darla
      DB_PASSWORD: 1234
      DB_NAME: chatflow
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
      - postgres
    volumes:
      - ./chatflow-backend:/chatflow
      - /chatflow/node_modules

  frontend:
    build:
      context: ./chatflow-frontend
      dockerfile: Dockerfile
    container_name: chatflow_frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./chatflow-frontend:/chatflow
      - /chatflow/node_modules
  redis:
    image: redis:latest
    container_name: chatflow_redis
    ports:
      - "6379:6379"
  
  postgres:
    image: postgres:16
    container_name: chatflow_postgres
    restart: always
    environment:
      POSTGRES_USER: darla
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: chatflow
      TZ: UTC
      PGTZ: UTC
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: