module.exports = {
  INVALID_REQUEST_BODY: "INVALID_REQUEST_BODY",
  VALIDATION_FAILED: "VALIDATION_FAILED",

  USER_NOT_FOUND: "USER_NOT_FOUND",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  MOBILE_ALREADY_EXISTS: "MOBILE_ALREADY_EXISTS",
  DUPLICATE_RECORD: "DUPLICATE_RECORD",

  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  UNAUTHORIZED: "UNAUTHORIZED",
  INVALID_TOKEN: "INVALID_TOKEN",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",

  INVALID_RESET_TOKEN: "INVALID_RESET_TOKEN",
  RESET_TOKEN_EXPIRED: "RESET_TOKEN_EXPIRED",

  FORBIDDEN: "FORBIDDEN",

  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",
  METHOD_NOT_ALLOWED: "METHOD_NOT_ALLOWED",

  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR"
};