version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: chatapp_redis
    ports:
      - "6379:6379"
  
  postgres:
    image: postgres:16
    container_name: chatapp_postgres
    restart: always
    environment:
      POSTGRES_USER: darla
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: chatapp_dev
      TZ: UTC
      PGTZ: UTC
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: