version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatapp_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: darla
      DB_PASSWORD: 1234
      DB_NAME: chatapp_dev
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/chatapp
      - /chatapp/node_modules

  redis:
    image: redis:latest
    container_name: chatapp_redis
    ports:
      - "6379:6379"
  
  postgres:
    image: postgres:16
    container_name: chatapp_postgres
    restart: always
    environment:
      POSTGRES_USER: darla
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: chatapp_dev
      TZ: UTC
      PGTZ: UTC
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: